# Use Maven + JDK image
FROM maven:3.9.6-eclipse-temurin-17

# Set working directory
WORKDIR /app

# Copy pom.xml first to leverage Maven cache
COPY pom.xml .

# Download dependencies only (faster rebuilds)
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Expose port your app will run on
EXPOSE 8081

# Run Spring Boot in dev mode
CMD ["mvn", "spring-boot:run"]
